### ISSUE TITLE
图片上方会多出来两行换行

### ISSUE THREAD

**Issue by Lhaihai** [CSUwangj/md2docx-csharp#1]
环境：Windows10  
软件：Word
md2docx-csharp版本：V2.1.1
![image](https://user-images.githubusercontent.com/25503472/74926482-ea940300-5410-11ea-966c-8f180193a2bd.png)

**Comment by CSUwangj** [comment]
使用时候应当直接在正文中嵌入图片，这样会自动让图片出现在之间，所以不要换行后再自行添加图片。
